site_name: "Pydantic Tornado"
site_author: "Dave Shawley"
repo_url: "https://github.com/dave-shawley/pydantic-tornado"
repo_name: "dave-shawley/pydantic-tornado"

theme:
  name: mkdocs-material-adr
  features:
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github

docs_dir: doc

nav:
  - index.md
  - User's Guide:
      - users-guide/examples.md
      - users-guide/writing-handlers.md
      - users-guide/injections.md
  - Reference:
      - reference/index.md
      - reference/api.md
  - Explanation:
      - adr/index.md
      - Decision Records:
          - adr/0001-record-architecture-decisions.md
          - adr/0002-generate-documentation-using-mkdocs.md
          - adr/0003-type-annotations.md

plugins:
  - autorefs
  - mkdocstrings:
      default_handler: python_xref
      enable_inventory: true
      handlers:
        python_xref:
          import:
            - "https://docs.python.org/3/objects.inv"
            - "https://www.tornadoweb.org/en/stable/objects.inv"
          options:
            docstring_style: "sphinx"
            docstring_section_style: "list"
            relative_crossrefs: true
            show_root_heading: true
            show_signature: true
            unwrap_annotated: true
  - mkdocs-material-adr/adr:
      graph_file: adr/index.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - sane_lists
  - toc:
      permalink: true
