name: "Publish"
on:
  push:
    branches: ["main"]
permissions:
  contents: write
jobs:
  publish_pages:
    name: "Publish to GitHub Pages"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Use github-actions user"
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: "Install hatch"
        run: |
          python -m pip install hatch
      - name: "Deploy docs"
        run: |
          hatch run github-pages
